apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: lab1-container
        image: bobaaboba9990/lab1-sum:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
